# Generated by Django 4.2 on 2023-05-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='course_images')),
                ('description', models.CharField(max_length=100)),
                ('course_amount', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Course_categories',
            },
        ),
    ]
