# Generated by Django 4.2 on 2023-05-01 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0004_course_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_category',
            name='name',
        ),
    ]
