# Generated by Django 4.2 on 2023-05-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0009_contactpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='formSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=400)),
                ('message', models.TextField()),
            ],
        ),
    ]
